language: node_js
notifications:
  irc:
    channels:
      - "irc.freenode.com#flocksjs"
      - "irc.blitzed.org#stonecypher-builds"
    template:
      - "%{repository} %{build_number} (%{commit}) : %{message} %{foo} "
  recipients:
    - stonecypher@gmail.com
node_js:
  - "0.11"
  - "0.10"
before_script: npm install
script: npm test